# Example Worker Configuration File
# Compute configuration files are identical 
# except for 'runtime' parameters.

# NOTE: 
# USER SHOULD NEVER CREATE/EDIT WORKER CONFIGRATION FILE. 
# WORKER CONFIGURATION FILE(S) ARE CREATED BY SCHEDULER NODE.

runtime: 
  # use_gpus: {True, False}
  use_gpus: False
  pool_size: 16

  # worker_cells: list of zyx coordinates of cells to run on this instance.
  # in which cell size is defined in 'algorithm_parameters'.
  # log_path: local path to write log file to. 
  #           Log file is given a unique name and written to specified directory. 
  worker:
    worker_cells: [...]
    log_path: "<YOUR PATH HERE>"

input: 
  # dataset_type: {big_stitcher, tiff_directory}
  # See bottom of config file for additional parameters.
  dataset_type: "BigStitcherDataset"

output: 
  # path: public bucket location (fused data too large to fit on disk)
  # chunksize: 5d tczyx shape
  # output_resolution: zyx resolution in units of um (or whatever the input resolution unit is). 
  path: "/root/capsule/scratch/tmp_output.zarr"
  chunksize: [1, 1, 128, 256, 256]
  resolution_zyx: [0.5, 0.5, 0.5]


algorithm_parameters: 
  # post_registration_transforms_zyx: list of transforms 
  #    to be applied after registration (such as deskewing). 
  # use_gpus: True for all system GPUs, False for CPU only
  # cell_size: zyx shape -- [1024, 512, 512] occupies 8 GPU GB.
  # blending_module: {MaxProjection, DeepBlend}
  post_registration_transforms_zyx: 
    - [[1, 0, -1, 0], 
       [0, 1, 0, 0], 
       [0, 0, 1, 0]]
  cell_size: [512, 512, 512]
  blending_module: MaxProjection


dataset_parameters: 
  BigStitcherDataset: 
    # xml_path: local path to find solution xml
    # s3_path: cloud path to dataset tiles
    xml_path: "<YOUR PATH HERE>"
    s3_path: "s3://<YOUR PATH HERE>"