# Example SoloNode Configuration File
# Compute configuration files are identical 
# except for 'runtime' parameters.

runtime: 
  distributed: False

input: 
  # dataset_type: {big_stitcher, tiff_directory}
  # See bottom of config file for additional parameters.
  dataset_type: "big_stitcher"


output: 
  # path: public bucket location (fused data too large to fit on disk)
  # chunksize: 5d tczyx shape
  # output_resolution: zyx resolution in units of um (or whatever the input resolution unit is). 
  path: "/root/capsule/scratch/tmp_output.zarr"
  chunksize: [1, 1, 128, 256, 256]
  resolution_zyx: [0.5, 0.5, 0.5]


algorithm_parameters: 
  # post_registration_transforms_zyx: list of transforms 
  #    to be applied after registration (such as deskewing). 
  # use_gpus: True for all system GPUs, False for CPU only
  # cell_size: zyx shape -- [1024, 512, 512] occupies 8 GPU GB.
  # blending_module: {MaxProjection, DeepBlend}
  post_registration_transforms_zyx: 
    - [[1, 0, -1, 0], 
       [0, 1, 0, 0], 
       [0, 0, 1, 0]]
  use_gpus: False
  cell_size: [512, 512, 512]
  blending_module: MaxProjection


dataset_parameters: 
  big_stitcher: 
    xml_path: "/root/capsule/data/Christian-ME-New-Lasers_stitch_output/bigstitcher_Christian-ME-New-Lasers.xml"